### ISSUE TITLE
Increase font-weight and add transitions to newsletter form submit button

### ISSUE THREAD

**Issue by colinkiama** [colinkiama/colinkiama-www#10]
- Use a font weight of `Medium` or `Semi-Bold`.
- Add a transition for the background color

**Comment by Pathholder1806** [comment]
Hey @colinkiama !
I would like to contribute to this issue.

**Comment by garvpatidar04** [comment]
Hello @colinkiama 
I would like to contribute to this issue, can you assign me this issue?

**Comment by Pathholder1806** [comment]
Hey @colinkiama !
Kindly review the PR I opened for my proposed fix. Thanks!

**Comment by colinkiama** [comment]
@garvpatidar04 sorry, they were much faster 😅
